import { StyleSheet } from 'react-native';
import { baseStyles } from './base';

export const bookStyles = StyleSheet.create({
  ...baseStyles,
  container: {
    display: 'flex',
    flex: 1,
  },
  backButton: {
    height: 50, 
    width: 50,
    padding: 8,
    top: 8,
    left: 16,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    alignItems: 'center',
    justifyContent: 'center'
  },
  header: {
    flexDirection: 'row',
    padding: 20,
    borderBottomWidth: 1,
    marginTop: 60,
    backgroundColor: 'transparent',
  },
  coverContainer: {
    width: 150,
    height: 210,
    marginRight: 20,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  cover: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
  },
  placeholderCover: {
    width: '100%',
    height: '100%',
    backgroundColor: '#f0f0f0',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  info: {
    flex: 1,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  author: {
    fontSize: 16,
    marginBottom: 12,
    opacity: 0.8,
  },
  metadata: {
    fontSize: 14,
    marginBottom: 4,
    opacity: 0.9,
  },
  metadataContainer: {
    paddingVertical: 16,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    marginVertical: 12,
  },
  metadataItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  metadataIcon: {
    marginRight: 10,
    width: 16,
    opacity: 0.8,
  },
  section: {
    padding: 20,
    borderBottomWidth: 1,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  description: {
    fontSize: 15,
    lineHeight: 24,
    opacity: 0.9,
  },
  ratingContainer: {
    flexDirection: 'row',
    marginBottom: 12,
    justifyContent: 'center',
  },
  star: {
    marginRight: 8,
  },
  ratingText: {
    fontSize: 14,
    textAlign: 'center',
    opacity: 0.8,
  },
  textInput: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    fontSize: 15,
  },
  addButton: {
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  addButtonText: {
    fontWeight: 'bold',
    fontSize: 15,
  },
  notesContainer: {
    marginTop: 12,
  },
  note: {
    marginBottom: 12,
    padding: 16,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  noteHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  notePage: {
    fontSize: 13,
    opacity: 0.8,
  },
  noteContent: {
    fontSize: 15,
    lineHeight: 22,
  },
  deleteButton: {
    padding: 6,
    borderRadius: 6,
  },
  emptyState: {
    fontSize: 15,
    textAlign: 'center',
    marginTop: 12,
    opacity: 0.7,
  },
  errorText: {
    fontSize: 16,
    textAlign: 'center',
    marginTop: 16,
  },
  removeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
    borderRadius: 8,
    margin: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  removeButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  statusSelector: {
    flexDirection: 'row',
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
    position: 'relative',
  },
  slider: {
    position: 'absolute',
    width: '50%',
    height: '100%',
    borderRadius: 20,
  },
  statusButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  statusButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
}); 